### ISSUE TITLE
Remove dot ?

### ISSUE THREAD

**Issue by raphaelgoetter** [gem0303/work-heatmap#1]
Hello,

Is it possible to modify user preferences in order to remove the dot next to the line number ? (it confuses with color dots of many extensions like this one : https://github.com/cmgddd/Brackets-css-color-preview )

I would just keep the bar in the scrollbar track.

Thank you

**Comment by gem0303** [comment]
Hi there! I'll look into setting up the user preferences later this week (hopefully Friday). Until I have the update working (and if you're comfortable editing the extension code itself) in main.js you can comment out the function showGutterMarks on lines 92 and 268 to disable the dots.

**Comment by raphaelgoetter** [comment]
Great, thank you.

**Comment by gem0303** [comment]
If you grab version 1.1 and add "work-heatmap.gutterEnabled": false to your user prefs file, you should be all set. :)

**Comment by raphaelgoetter** [comment]
works great, thank you !
