### ISSUE TITLE
No heatmap display- Brackets Release 1.7 build 1.7.0-16898

### ISSUE THREAD

**Issue by trick99** [gem0303/work-heatmap#2]
Nice idea, but I dont see any heatmap DOTS in my brackets editor. Scrollbar lines are displayed. Confirmed 'Work Heatmap' is checked. 
Brackets Release 1.7 build 1.7.0-16898 , Theme: tried both dark and light

**Comment by gem0303** [comment]
Hi there, sorry to hear you're having trouble with the extension! I've used it today on two different computers and am not able to replicate the error of the dots not showing. This leads me to believe you either have a different version of Brackets from what I'm using, or you are running an extension that conflicts with Work Heatmap. Would you be willing to share a list of extensions you have installed, and what Brackets release you're on?

**Comment by trick99** [comment]
After using for about 1 hour, I'm starting to see dots now!!

[https://s13.postimg.org/do9h1wrzr/brackets.png](url)
Brackets Release 1.7 build 1.7.0-16898
Extensions:  Brackets Wordpress Hint (3.2.0), Super Right Click(1.0.2)

I'm sure this is not reasonable explanation, and someone may assume I just didn't notice it before. But I'm kinda sure of it, since I initially raised an issue for scrollbar lines not appearing, minutes before it started appearing. It happened again -  withing half an hour after raising issue for dots, they magically started appearing too..

Sorry for trouble if this makes no sense programmatically.  Addon is working now. Thanks, great work!.

**Comment by gem0303** [comment]
Thanks for the quick reply and I'm glad to hear the extension is working for you now! Looks like your build is up to date so I'll check out the two extensions you listed and see if I can reproduce the issue.

There's a known bug that the first 1-2 times you make an edit in the file, that change won't be logged by the heatmap. But it's very strange to hear that it took so much longer for yours to kick in. I'll recruit some ~~victims~~ testers on Monday and see if this issue pops up.
